### ISSUE TITLE
支持无限重试gid强制终止

### ISSUE THREAD

**Issue by Rennbon** [dtm-labs/dtf#1]
因为线上环境会有一些特殊异常，如上线时路径配错了，请求了错误路径，这种不需要正常修复，也不能将错就错在错误的方案上做弥补，这类重试的gid强制关闭即可，可以从组织架构上走审批来确保不会出错。

**Comment by yedf2** [comment]
帮忙提个pr？允许将全局事务的状态，直接设置为failed
这个在未来dtf有管理后台是，会开发相关界面

**Comment by Rennbon** [comment]
> 帮忙提个pr？允许将全局事务的状态，直接设置为failed 这个在未来dtf有管理后台是，会开发相关界面

OK的

**Comment by yedf2** [comment]
我仔细思考了这个异常终止的case，目前你的实现是把这个原因保存到ext_data里面，但是这个字段是用于存储全局事务额外信息的，不是结果，因此不太合适。
最好的方式估计是要再加一个字段，但是这样复杂度又增加了，我计划把这个加字段的事情，延后到未来管理后台开发的时候，避免现在的设计和未来出现冲突。
本来这个异常终止就相当于DBA直接改数据库，因此我认为这个功能的实现不记录原因，就仅仅是把status改为failed，这样就不会过度设计

**Comment by yedf2** [comment]
我仔细思考了这个异常终止的case，目前你的实现是把这个原因保存到ext_data里面，但是这个字段是用于存储全局事务额外信息的，不是结果，因此不太合适。
最好的方式估计是要再加一个字段，但是这样复杂度又增加了，我计划把这个加字段的事情，延后到未来管理后台开发的时候，避免现在的设计和未来出现冲突。
本来这个异常终止就相当于DBA直接改数据库，因此我认为这个功能的实现不记录原因，就仅仅是把status改为failed，这样就不会过度设计
