### ISSUE TITLE
是否有考虑和dapr进行集成

### ISSUE THREAD

**Issue by kamikyo** [dtm-labs/dtf#11]
拜读了您的架构设计，感觉其和dapr的思想不谋而合。刚好，dtm也是使用go研发的，是否考虑借助dapr的生态，做一个dapr的component来进一步扩充dapr的生态，也让更多的人了解到dtm这一优秀的设计思想

**Comment by yedf2** [comment]
目前我的精力有限。如果社区有同学有兴趣，欢迎pr哈
